name: Swift Package

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: SPM Build
      run: swift build
    - name: SPM Test
      run: swift test
    - name: macOS Build
      run: xcodebuild build -scheme B9Condition -destination 'generic/platform=macOS' | xcpretty
    - name: iOS Build
      run: xcodebuild build -scheme B9Condition -destination 'generic/platform=iOS' | xcpretty
    - name: tvOS Build
      run: xcodebuild build -scheme B9Condition -destination 'generic/platform=tvOS' | xcpretty
    - name: watchOS Build
      run: xcodebuild build -scheme B9Condition -destination 'generic/platform=watchOS' | xcpretty
